# Generated by Django 4.0.4 on 2022-06-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_catogary_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catogary',
            new_name='catogory',
        ),
    ]
