# Generated by Django 4.0.4 on 2022-07-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_orders_address_alter_orders_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('udate_desc', models.CharField(max_length=9000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
