# Generated by Django 4.0.4 on 2022-07-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_ordersupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersupdate',
            old_name='udate_desc',
            new_name='update_desc',
        ),
    ]
